# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ko-KR"

reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  review_status: true
  review_details: false
  poem: false
  pre_merge_checks:
    docstrings:
      mode: "off"
  path_filters:
    - "!**/build/**"
    - "!**/.gradle/**"
    - "!**/.idea/**"
    - "!**/out/**"
    - "!**/*.iml"
    - "!**/.env"
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "develop"
      - "main"

chat:
  auto_reply: true