-- PLIMAP initial schema (PostgreSQL/PostGIS)

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE member
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nickname                 VARCHAR(7),
    name                     VARCHAR(7),
    introduction             VARCHAR(100),
    profile_image_object_key VARCHAR(500),
    status                   VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    onboarding_completed_at  TIMESTAMPTZ,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at               TIMESTAMPTZ,
    CONSTRAINT pk_member PRIMARY KEY (id),
    CONSTRAINT chk_member_nickname_length
        CHECK (nickname IS NULL OR char_length(nickname) BETWEEN 2 AND 7),
    CONSTRAINT chk_member_nickname_format
        CHECK (nickname IS NULL OR nickname ~ '^[가-힣A-Za-z0-9]+$'),
    CONSTRAINT chk_member_name_length
        CHECK (name IS NULL OR char_length(name) BETWEEN 1 AND 7),
    CONSTRAINT chk_member_name_format
        CHECK (name IS NULL OR name ~ '^[가-힣A-Za-z0-9]+$'),
    CONSTRAINT chk_member_status
        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN')),
    CONSTRAINT chk_member_onboarding
        CHECK (onboarding_completed_at IS NULL OR nickname IS NOT NULL)
);

CREATE UNIQUE INDEX uk_member_nickname_ci
    ON member (lower(nickname))
    WHERE nickname IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE member_follow
(
    follower_id  BIGINT      NOT NULL,
    following_id BIGINT      NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_member_follow PRIMARY KEY (follower_id, following_id),
    CONSTRAINT fk_member_follow_follower
        FOREIGN KEY (follower_id) REFERENCES member (id) ON DELETE CASCADE,
    CONSTRAINT fk_member_follow_following
        FOREIGN KEY (following_id) REFERENCES member (id) ON DELETE CASCADE,
    CONSTRAINT chk_member_follow_self CHECK (follower_id <> following_id)
);

CREATE INDEX idx_member_follow_following_id ON member_follow (following_id);

CREATE TABLE social_account
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id        BIGINT       NOT NULL,
    provider         VARCHAR(20)  NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    email            VARCHAR(320),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_social_account PRIMARY KEY (id),
    CONSTRAINT uk_social_account_provider_subject UNIQUE (provider, provider_subject),
    CONSTRAINT uk_social_account_member_provider UNIQUE (member_id, provider),
    CONSTRAINT fk_social_account_member
        FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE CASCADE,
    CONSTRAINT chk_social_account_provider
        CHECK (provider IN ('KAKAO', 'GOOGLE', 'APPLE'))
);

CREATE INDEX idx_social_account_member ON social_account (member_id);

CREATE TABLE terms
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type         VARCHAR(20)  NOT NULL,
    version      VARCHAR(20)  NOT NULL,
    title        VARCHAR(200) NOT NULL,
    content      TEXT         NOT NULL,
    is_required  BOOLEAN      NOT NULL DEFAULT TRUE,
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    effective_at TIMESTAMPTZ  NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_terms PRIMARY KEY (id),
    CONSTRAINT uk_terms_type_version UNIQUE (type, version),
    CONSTRAINT chk_terms_type
        CHECK (type IN ('SERVICE', 'PRIVACY', 'LOCATION', 'MARKETING'))
);

CREATE INDEX idx_terms_active ON terms (type, is_active, effective_at DESC);

CREATE TABLE member_terms_agreement
(
    member_id    BIGINT      NOT NULL,
    terms_id     BIGINT      NOT NULL,
    agreed       BOOLEAN     NOT NULL,
    agreed_at    TIMESTAMPTZ,
    withdrawn_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_member_terms_agreement PRIMARY KEY (member_id, terms_id),
    CONSTRAINT fk_member_terms_agreement_member
        FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE CASCADE,
    CONSTRAINT fk_member_terms_agreement_terms
        FOREIGN KEY (terms_id) REFERENCES terms (id) ON DELETE RESTRICT,
    CONSTRAINT chk_member_terms_agreed_at CHECK (agreed = FALSE OR agreed_at IS NOT NULL)
);

CREATE INDEX idx_member_terms_agreement_terms ON member_terms_agreement (terms_id);

CREATE TABLE place
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name              VARCHAR(100) NOT NULL,
    address           VARCHAR(255) NOT NULL,
    road_address      VARCHAR(255),
    place_provider    VARCHAR(30),
    provider_place_id VARCHAR(255),
    source            VARCHAR(20)  NOT NULL,
    location          GEOGRAPHY(POINT, 4326) NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at        TIMESTAMPTZ,
    CONSTRAINT pk_place PRIMARY KEY (id),
    CONSTRAINT chk_place_source CHECK (source IN ('PLACE_SEARCH', 'MAP_SELECTION')),
    CONSTRAINT chk_place_location_not_empty CHECK (NOT ST_IsEmpty(location::geometry)),
    CONSTRAINT chk_place_provider CHECK (
        (
            source = 'PLACE_SEARCH'
            AND place_provider IS NOT NULL
            AND provider_place_id IS NOT NULL
        )
        OR (
            source = 'MAP_SELECTION'
            AND place_provider IS NULL
            AND provider_place_id IS NULL
        )
    )
);

CREATE UNIQUE INDEX uk_place_provider_id
    ON place (place_provider, provider_place_id)
    WHERE place_provider IS NOT NULL
      AND provider_place_id IS NOT NULL
      AND deleted_at IS NULL;

CREATE INDEX idx_place_location_gist
    ON place USING GIST (location)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_place_name_ci
    ON place (lower(name))
    WHERE deleted_at IS NULL;

CREATE TABLE place_bookmark
(
    place_id   BIGINT      NOT NULL,
    member_id  BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_place_bookmark PRIMARY KEY (place_id, member_id),
    CONSTRAINT fk_place_bookmark_place
        FOREIGN KEY (place_id) REFERENCES place (id) ON DELETE CASCADE,
    CONSTRAINT fk_place_bookmark_member
        FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE CASCADE
);

CREATE INDEX idx_place_bookmark_member ON place_bookmark (member_id, created_at DESC);

CREATE TABLE place_search_history
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id         BIGINT       NOT NULL,
    place_id          BIGINT,
    place_provider    VARCHAR(30),
    provider_place_id VARCHAR(255),
    place_name        VARCHAR(100) NOT NULL,
    category          VARCHAR(100),
    address           VARCHAR(255) NOT NULL,
    location          GEOGRAPHY(POINT, 4326) NOT NULL,
    selected_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_place_search_history PRIMARY KEY (id),
    CONSTRAINT fk_place_search_history_member
        FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE CASCADE,
    CONSTRAINT fk_place_search_history_place
        FOREIGN KEY (place_id) REFERENCES place (id) ON DELETE CASCADE,
    CONSTRAINT chk_place_search_history_target CHECK (
        place_id IS NOT NULL
        OR (place_provider IS NOT NULL AND provider_place_id IS NOT NULL)
    ),
    CONSTRAINT chk_place_search_history_provider CHECK (
        (place_provider IS NULL AND provider_place_id IS NULL)
        OR (place_provider IS NOT NULL AND provider_place_id IS NOT NULL)
    ),
    CONSTRAINT chk_place_search_history_location_not_empty
        CHECK (NOT ST_IsEmpty(location::geometry))
);

CREATE INDEX idx_place_search_history_member_recent
    ON place_search_history (member_id, selected_at DESC);

CREATE UNIQUE INDEX uk_place_search_history_member_place
    ON place_search_history (member_id, place_id)
    WHERE place_id IS NOT NULL;

CREATE UNIQUE INDEX uk_place_search_history_member_provider
    ON place_search_history (member_id, place_provider, provider_place_id)
    WHERE place_provider IS NOT NULL AND provider_place_id IS NOT NULL;

CREATE TABLE track
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    provider          VARCHAR(30)  NOT NULL,
    provider_track_id VARCHAR(255) NOT NULL,
    title             VARCHAR(200) NOT NULL,
    artist_name       VARCHAR(200) NOT NULL,
    album_title       VARCHAR(200),
    album_image_url   VARCHAR(1000),
    preview_url       VARCHAR(1000),
    duration_ms       INTEGER,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_track PRIMARY KEY (id),
    CONSTRAINT uk_track_provider_id UNIQUE (provider, provider_track_id),
    CONSTRAINT chk_track_duration CHECK (duration_ms IS NULL OR duration_ms >= 0)
);

CREATE INDEX idx_track_title_ci ON track (lower(title));
CREATE INDEX idx_track_artist_ci ON track (lower(artist_name));

CREATE TABLE place_track
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    place_id         BIGINT      NOT NULL,
    track_id         BIGINT      NOT NULL,
    public_pin_count INTEGER     NOT NULL DEFAULT 0,
    like_count       INTEGER     NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at       TIMESTAMPTZ,
    CONSTRAINT pk_place_track PRIMARY KEY (id),
    CONSTRAINT uk_place_track_id_place UNIQUE (id, place_id),
    CONSTRAINT fk_place_track_place
        FOREIGN KEY (place_id) REFERENCES place (id) ON DELETE CASCADE,
    CONSTRAINT fk_place_track_track
        FOREIGN KEY (track_id) REFERENCES track (id) ON DELETE RESTRICT,
    CONSTRAINT chk_place_track_public_pin_count CHECK (public_pin_count >= 0),
    CONSTRAINT chk_place_track_like_count CHECK (like_count >= 0)
);

CREATE UNIQUE INDEX uk_place_track_active
    ON place_track (place_id, track_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_place_track_track
    ON place_track (track_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_place_track_place_popular
    ON place_track (place_id, like_count DESC, id DESC)
    WHERE deleted_at IS NULL AND public_pin_count > 0;

CREATE INDEX idx_place_track_place_latest
    ON place_track (place_id, created_at DESC, id DESC)
    WHERE deleted_at IS NULL AND public_pin_count > 0;

CREATE TABLE place_track_like
(
    place_track_id BIGINT      NOT NULL,
    member_id      BIGINT      NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_place_track_like PRIMARY KEY (place_track_id, member_id),
    CONSTRAINT fk_place_track_like_place_track
        FOREIGN KEY (place_track_id) REFERENCES place_track (id) ON DELETE CASCADE,
    CONSTRAINT fk_place_track_like_member
        FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE CASCADE
);

CREATE INDEX idx_place_track_like_member
    ON place_track_like (member_id, created_at DESC);

CREATE TABLE pin
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id      BIGINT       NOT NULL,
    place_id       BIGINT       NOT NULL,
    place_track_id BIGINT       NOT NULL,
    clip_start_ms  INTEGER      NOT NULL,
    clip_end_ms    INTEGER      NOT NULL,
    introduction   VARCHAR(100) NOT NULL DEFAULT '',
    is_feed_public BOOLEAN      NOT NULL DEFAULT TRUE,
    like_count     INTEGER      NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at     TIMESTAMPTZ,
    CONSTRAINT pk_pin PRIMARY KEY (id),
    CONSTRAINT fk_pin_member
        FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE RESTRICT,
    CONSTRAINT fk_pin_place_track
        FOREIGN KEY (place_track_id, place_id)
        REFERENCES place_track (id, place_id) ON DELETE CASCADE,
    CONSTRAINT chk_pin_clip_start CHECK (clip_start_ms >= 0),
    CONSTRAINT chk_pin_clip_range CHECK (clip_end_ms > clip_start_ms),
    CONSTRAINT chk_pin_introduction CHECK (char_length(introduction) <= 100),
    CONSTRAINT chk_pin_like_count CHECK (like_count >= 0)
);

CREATE UNIQUE INDEX uk_pin_member_place_active
    ON pin (member_id, place_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_pin_place_created
    ON pin (place_id, created_at DESC)
    WHERE deleted_at IS NULL AND is_feed_public = TRUE;

CREATE INDEX idx_pin_place_track_popular
    ON pin (place_track_id, like_count DESC, id DESC)
    WHERE deleted_at IS NULL AND is_feed_public = TRUE;

CREATE INDEX idx_pin_place_track_latest
    ON pin (place_track_id, created_at DESC, id DESC)
    WHERE deleted_at IS NULL AND is_feed_public = TRUE;

CREATE TABLE tag
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(20) NOT NULL,
    display_order SMALLINT    NOT NULL,
    is_active     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_tag PRIMARY KEY (id),
    CONSTRAINT uk_tag_display_order UNIQUE (display_order),
    CONSTRAINT chk_tag_name_not_blank CHECK (char_length(name) BETWEEN 1 AND 20),
    CONSTRAINT chk_tag_name_trimmed CHECK (name = trim(name)),
    CONSTRAINT chk_tag_name_without_hash CHECK (position('#' IN name) = 0),
    CONSTRAINT chk_tag_display_order CHECK (display_order >= 0)
);

CREATE UNIQUE INDEX uk_tag_name_ci ON tag (lower(name));

INSERT INTO tag (name, display_order)
VALUES ('감성', 0),
       ('고독', 1),
       ('낭만', 2),
       ('몽환', 3),
       ('설렘', 4),
       ('신남', 5),
       ('위로', 6),
       ('잔잔', 7),
       ('청량', 8),
       ('힙함', 9);

CREATE TABLE pin_tag
(
    pin_id        BIGINT      NOT NULL,
    tag_id        BIGINT      NOT NULL,
    display_order SMALLINT    NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_pin_tag PRIMARY KEY (pin_id, tag_id),
    CONSTRAINT uk_pin_tag_order UNIQUE (pin_id, display_order),
    CONSTRAINT fk_pin_tag_pin
        FOREIGN KEY (pin_id) REFERENCES pin (id) ON DELETE CASCADE,
    CONSTRAINT fk_pin_tag_tag
        FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE RESTRICT,
    CONSTRAINT chk_pin_tag_order CHECK (display_order BETWEEN 0 AND 3)
);

CREATE INDEX idx_pin_tag_tag ON pin_tag (tag_id);

CREATE TABLE pin_like
(
    pin_id     BIGINT      NOT NULL,
    member_id  BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_pin_like PRIMARY KEY (pin_id, member_id),
    CONSTRAINT fk_pin_like_pin
        FOREIGN KEY (pin_id) REFERENCES pin (id) ON DELETE CASCADE,
    CONSTRAINT fk_pin_like_member
        FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE CASCADE
);

CREATE INDEX idx_pin_like_member ON pin_like (member_id, created_at DESC);
