INSERT INTO terms (type, version, title, content, is_required, is_active, effective_at)
VALUES
    ('SERVICE',
     'v1',
     '플리맵 이용약관',
     '플리맵 서비스 이용에 관한 기본적인 조건과 절차, 회원과 회사의 권리·의무 및 책임사항을 규정합니다.',
     TRUE,
     TRUE,
     CURRENT_TIMESTAMP),
    ('PRIVACY',
     'v1',
     '개인정보 수집 및 이용 동의',
     '회원가입 및 서비스 제공을 위해 수집하는 개인정보 항목, 수집·이용 목적, 보유 및 이용 기간을 안내합니다.',
     TRUE,
     TRUE,
     CURRENT_TIMESTAMP),
    ('LOCATION',
     'v1',
     '위치기반서비스 이용약관',
     '지도 기반 장소·음악 기록 기능 제공을 위한 위치정보 수집·이용에 관한 사항을 규정합니다.',
     TRUE,
     TRUE,
     CURRENT_TIMESTAMP),
    ('MARKETING',
     'v1',
     '마케팅 정보 수신 동의',
     '이벤트, 혜택 등 마케팅 목적의 광고성 정보를 이메일·푸시 알림 등으로 수신하는 것에 대한 동의입니다.',
     FALSE,
     TRUE,
     CURRENT_TIMESTAMP);
