CREATE TABLE notification
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    recipient_id BIGINT      NOT NULL,
    actor_id     BIGINT      NOT NULL,
    pin_id       BIGINT,
    type         TEXT        NOT NULL,
    read_at      TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_notification PRIMARY KEY (id),
    CONSTRAINT fk_notification_recipient
        FOREIGN KEY (recipient_id) REFERENCES member (id) ON DELETE RESTRICT,
    CONSTRAINT fk_notification_actor
        FOREIGN KEY (actor_id) REFERENCES member (id) ON DELETE RESTRICT,
    CONSTRAINT fk_notification_pin
        FOREIGN KEY (pin_id) REFERENCES pin (id) ON DELETE RESTRICT,
    CONSTRAINT chk_notification_type
        CHECK (type IN ('FOLLOW', 'PIN_CREATED', 'PIN_LIKED')),
    CONSTRAINT chk_notification_pin_required
        CHECK (
            (type = 'FOLLOW' AND pin_id IS NULL)
            OR (type IN ('PIN_CREATED', 'PIN_LIKED') AND pin_id IS NOT NULL)
        )
);

CREATE INDEX idx_notification_recipient_created_at
    ON notification (recipient_id, created_at DESC, id DESC);
