CREATE TABLE inquiry
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id      BIGINT,
    category       TEXT          NOT NULL,
    title          VARCHAR(100)  NOT NULL,
    content        TEXT          NOT NULL,
    contact_email  VARCHAR(320)  NOT NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_inquiry PRIMARY KEY (id),
    CONSTRAINT fk_inquiry_member
        FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE SET NULL,
    CONSTRAINT chk_inquiry_category
        CHECK (
            category IN (
                'ACCOUNT_SUSPENSION_OR_WITHDRAWAL',
                'LOGIN_AUTH_ERROR',
                'PIN_REGISTRATION_OR_PLAYBACK_ERROR',
                'REPORT_SANCTION_APPEAL',
                'APP_BUG_OR_ERROR',
                'OTHER'
            )
        ),
    CONSTRAINT chk_inquiry_title
        CHECK (char_length(btrim(title)) >= 1),
    CONSTRAINT chk_inquiry_content
        CHECK (char_length(btrim(content)) >= 1),
    CONSTRAINT chk_inquiry_contact_email
        CHECK (char_length(btrim(contact_email)) >= 1)
);

CREATE INDEX idx_inquiry_member_id ON inquiry (member_id);
