CREATE TABLE report
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    reporter_member_id BIGINT      NOT NULL,
    reported_member_id BIGINT,
    reported_pin_id    BIGINT,
    category           TEXT        NOT NULL,
    detail             TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_report PRIMARY KEY (id),
    CONSTRAINT fk_report_reporter_member
        FOREIGN KEY (reporter_member_id) REFERENCES member (id) ON DELETE RESTRICT,
    CONSTRAINT fk_report_reported_member
        FOREIGN KEY (reported_member_id) REFERENCES member (id) ON DELETE RESTRICT,
    CONSTRAINT fk_report_reported_pin
        FOREIGN KEY (reported_pin_id) REFERENCES pin (id) ON DELETE RESTRICT,
    CONSTRAINT chk_report_target
        CHECK (
            (reported_member_id IS NOT NULL AND reported_pin_id IS NULL)
            OR (reported_member_id IS NULL AND reported_pin_id IS NOT NULL)
        ),
    CONSTRAINT chk_report_member_self
        CHECK (reported_member_id IS NULL OR reporter_member_id <> reported_member_id),
    CONSTRAINT chk_report_category
        CHECK (
            category IN (
                'PERSONAL_INFORMATION_EXPOSURE',
                'OBSCENE_OR_HARMFUL',
                'ABUSE_OR_HATE_SPEECH',
                'COMMERCIAL_OR_PROMOTIONAL',
                'OTHER'
            )
        ),
    CONSTRAINT chk_report_detail
        CHECK (
            (category = 'OTHER' AND detail IS NOT NULL AND char_length(btrim(detail)) >= 1)
            OR (category <> 'OTHER' AND detail IS NULL)
        )
);

CREATE UNIQUE INDEX uk_report_reporter_member
    ON report (reporter_member_id, reported_member_id)
    WHERE reported_member_id IS NOT NULL;

CREATE UNIQUE INDEX uk_report_reporter_pin
    ON report (reporter_member_id, reported_pin_id)
    WHERE reported_pin_id IS NOT NULL;
